In [1]:
import numpy as np
import pandas as pd
import os
from functools import reduce

**ALL Genes**

In [2]:
# get the files
msigdb_all_df = pd.read_csv('C:/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/ML_input_files/ClosenessCentrality_tables/msigdb/local_basal_all.csv')
GO_all_df = pd.read_csv('C:/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/ML_input_files/ClosenessCentrality_tables/GO/local_basal_all.csv')

# Drop the first column "previous row numbers of dataframe"
msigdb_all_df = msigdb_all_df.drop(msigdb_all_df.columns[0], axis=1)
GO_all_df = GO_all_df.drop(GO_all_df.columns[0], axis=1)

# Remove row numbers (index)
msigdb_all_df.reset_index(drop=True, inplace=True)
GO_all_df.reset_index(drop=True, inplace=True)

In [3]:
msigdb_all_df

,hgnc_symbol,M1,M10,M1002,M10041,M10065,M1007,M1011,M10117,M1012,...,M9936,M9940,M9945,M9946,M9948,M9951,M998,M9982,M999,M9990
0,A1BG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A1CF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A2M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A2ML1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A3GALT2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15389,ZXDC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15390,ZYG11A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15391,ZYG11B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15392,ZYX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0
15393,ZZEF1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
GO_all_df

,hgnc_symbol,GO:0000139,GO:0000228,GO:0000307,GO:0000323,GO:0000502,GO:0000775,GO:0000776,GO:0000779,GO:0000781,...,GO:2001056,GO:2001187,GO:2001204,GO:2001233,GO:2001235,GO:2001236,GO:2001237,GO:2001238,GO:2001242,GO:2001251
0,A1BG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A1CF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A2M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A2ML1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A3GALT2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15389,ZXDC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15390,ZYG11A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15391,ZYG11B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15392,ZYX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15393,ZZEF1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# combine dataframes
results_all_df = pd.merge(msigdb_all_df, GO_all_df, how='outer', on='hgnc_symbol')

In [6]:
# Sort the genes ID alphabetically
results_all_df = results_all_df.sort_values('hgnc_symbol')

In [7]:
results_all_df

,hgnc_symbol,M1,M10,M1002,M10041,M10065,M1007,M1011,M10117,M1012,...,GO:2001056,GO:2001187,GO:2001204,GO:2001233,GO:2001235,GO:2001236,GO:2001237,GO:2001238,GO:2001242,GO:2001251
0,A1BG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A1CF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A2M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A2ML1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A3GALT2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15389,ZXDC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15390,ZYG11A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15391,ZYG11B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15392,ZYX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15393,ZZEF1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
# check duplicated values in the 'hgnc_symbol' column
duplicates = results_all_df[results_all_df.duplicated('hgnc_symbol', keep=False)]
duplicates

Empty DataFrame
Columns: [hgnc_symbol, M1, M10, M1002, M10041, M10065, M1007, M1011, M10117, M1012, M10134, M10137, M10142, M10146, M10161, M10165, M10169, M1017, M10184, M10189, M10190, M10197, M1021, M10236, M10237, M10242, M10253, M10279, M10292, M1030, M10311, M10319, M10320, M10322, M10327, M10351, M1037, M10372, M10381, M10388, M1039, M104, M1040, M10404, M10414, M10420, M10427, M10431, M10439, M10454, M1047, M10480, M1050, M10501, M10504, M10508, M10511, M1053, M10554, M10558, M1056, M10573, M1058, M10593, M10599, M106, M1060, M10605, M1062, M1066, M10660, M10668, M10680, M10688, M10693, M107, M10702, M1073, M10739, M1074, M10746, M1075, M10783, M1079, M10791, M10797, M1080, M1081, M10814, M10861, M10866, M10880, M10888, M10899, M10909, M10917, M10952, M1096, M10961, M1097, ...]
Index: []

[0 rows x 4346 columns]

In [9]:
# Save the DataFrame as a CSV file
results_all_df.to_csv(r'C:/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/ML_input_files/ClosenessCentrality_tables/msigdb_and_GO/local_basal_all.csv')

**POSITIVE Genes**

In [10]:
# get the files
msigdb_positive_df = pd.read_csv('C:/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/ML_input_files/ClosenessCentrality_tables/msigdb/local_basal_positive.csv')
GO_positive_df = pd.read_csv('C:/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/ML_input_files/ClosenessCentrality_tables/GO/local_basal_positive.csv')

# Drop the first column "previous row numbers of dataframe"
msigdb_positive_df = msigdb_positive_df.drop(msigdb_positive_df.columns[0], axis=1)
GO_positive_df = GO_positive_df .drop(GO_positive_df .columns[0], axis=1)

# Remove row numbers (index)
msigdb_positive_df.reset_index(drop=True, inplace=True)
GO_positive_df .reset_index(drop=True, inplace=True)

In [11]:
msigdb_positive_df

,hgnc_symbol,M10041,M10134,M10165,M10184,M10197,M10236,M10237,M10279,M10320,...,M9483,M9516,M9524,M9585,M9639,M973,M9740,M9826,M983,M9893
0,A1CF,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
1,ABAT,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
2,ABCA3,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
3,ABCC8,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
4,ACE2,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,ZBTB16,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
611,ZNF185,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
612,ZNF365,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
613,ZNF469,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
614,ZWINT,0.0,0.0,0.0,0.0,0.0,0.001,0.0,0.0,0.0,...,0.0,0.001,0.0,0.001,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
GO_positive_df

,hgnc_symbol,GO:0000775,GO:0000776,GO:0000779,GO:0001533,GO:0005576,GO:0005581,GO:0005583,GO:0005604,GO:0005615,...,GO:1903828,GO:1903900,GO:1904950,GO:1904951,GO:1905818,GO:1990573,GO:2000026,GO:2000027,GO:2000145,GO:2000147
0,A1CF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
1,ABAT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
2,ABCA3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
3,ABCC8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.666667,0.0,0.666667,0.571429,0.0,0.857143,0.0,0.0,0.0,0.0
4,ACE2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,ZBTB16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
611,ZNF185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
612,ZNF365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
613,ZNF469,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
614,ZWINT,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,0.0,0.0,0.0

In [13]:
# combine dataframes
results_positive_df = pd.merge(msigdb_positive_df, GO_positive_df, how='outer', on='hgnc_symbol')

In [14]:
# Sort the genes ID alphabetically
results_positive_df = results_positive_df.sort_values('hgnc_symbol')

In [15]:
results_positive_df

,hgnc_symbol,M10041,M10134,M10165,M10184,M10197,M10236,M10237,M10279,M10320,...,GO:1903828,GO:1903900,GO:1904950,GO:1904951,GO:1905818,GO:1990573,GO:2000026,GO:2000027,GO:2000145,GO:2000147
0,A1CF,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
1,ABAT,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
2,ABCA3,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
3,ABCC8,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.666667,0.0,0.666667,0.571429,0.0,0.857143,0.0,0.0,0.0,0.0
4,ACE2,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,ZBTB16,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
611,ZNF185,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
612,ZNF365,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
613,ZNF469,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
614,ZWINT,0.0,0.0,0.0,0.0,0.0,0.001,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,0.0,0.0,0.0

In [16]:
# check duplicated values in the 'hgnc_symbol' column
duplicates_positive = results_positive_df[results_positive_df.duplicated('hgnc_symbol', keep=False)]
duplicates_positive

Empty DataFrame
Columns: [hgnc_symbol, M10041, M10134, M10165, M10184, M10197, M10236, M10237, M10279, M10320, M10351, M1037, M10372, M10431, M10439, M10454, M10480, M10501, M10508, M1058, M106, M1060, M10693, M10702, M10791, M10861, M10909, M10917, M11156, M11185, M1124, M11282, M1157, M11613, M11630, M1167, M11788, M11790, M11825, M11884, M1195, M11951, M11961, M12029, M12065, M12108, M12112, M12144, M12175, M12176, M12225, M12272, M12369, M12490, M12522, M12527, M126, M12602, M12636, M12671, M12746, M12769, M12795, M1280, M12804, M1286, M12868, M12890, M12987, M130, M13014, M13118, M13123, M132, M13206, M13251, M13273, M13283, M13406, M13422, M13453, M13547, M13566, M13809, M13867, M13944, M1406, M14072, M14076, M14108, M14121, M14134, M14151, M1424, M1432, M14340, M14358, M14371, M14427, M1443, ...]
Index: []

[0 rows x 1000 columns]

In [17]:
# Save the DataFrame as a CSV file
results_positive_df.to_csv(r'C:/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/ML_input_files/ClosenessCentrality_tables/msigdb_and_GO/local_basal_positive.csv')

**NEGATIVE Genes**

In [18]:
# get the files
msigdb_negative_df = pd.read_csv('C:/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/ML_input_files/ClosenessCentrality_tables/msigdb/local_basal_negative.csv')
GO_negative_df = pd.read_csv('C:/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/ML_input_files/ClosenessCentrality_tables/GO/local_basal_negative.csv')

# Drop the first column "previous row numbers of dataframe"
msigdb_negative_df = msigdb_negative_df.drop(msigdb_negative_df.columns[0], axis=1)
GO_negative_df = GO_negative_df.drop(GO_negative_df.columns[0], axis=1)

# Remove row numbers (index)
msigdb_negative_df.reset_index(drop=True, inplace=True)
GO_negative_df.reset_index(drop=True, inplace=True)

In [19]:
msigdb_negative_df

,hgnc_symbol,M10237,M1036,M10501,M11961,M12113,M13893,M14427,M149,M15619,...,M4077,M4409,M5275,M5336,M5611,M567,M6782,M80,M864,M9585
0,ABCB4,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
1,ABHD14B,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
2,ACER3,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
3,ACSM2A,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
4,ACTL6A,0.066667,0.0,0.0,0.266667,0.0,0.0,0.0,0.461538,0.0,...,0.0,0.0,0.0,0.0,0.05968,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,ZNF695,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
417,ZNF75D,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
418,ZNF835,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
419,ZNF90,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0
420,ZNFX1,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0

In [20]:
GO_negative_df

,hgnc_symbol,GO:0005622,GO:0005634,GO:0005654,GO:0005681,GO:0005739,GO:0005747,GO:0005759,GO:0005813,GO:0005815,...,GO:0042776,GO:0043412,GO:0043687,GO:0044248,GO:0044281,GO:0044419,GO:0046034,GO:0070647,GO:0098727,GO:0140888
0,ABCB4,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,ABHD14B,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,ACER3,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,ACSM2A,0.000000,0.000000,0.000000,0.0,0.3,0.0,0.666667,0.0,0.0,...,0.0,0.0,0.0,0.0,0.333333,0.0,0.0,0.0,0.0,0.0
4,ACTL6A,0.415638,0.448052,0.477477,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,ZNF695,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
417,ZNF75D,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
418,ZNF835,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
419,ZNF90,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
420,ZNFX1,0.286119,0.302632,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,0.0,0.0,0.0

In [21]:
# combine dataframes
results_negative_df = pd.merge(msigdb_negative_df, GO_negative_df, how='outer', on='hgnc_symbol')

In [22]:
# Sort the genes ID alphabetically
results_negative_df = results_negative_df.sort_values('hgnc_symbol')

In [23]:
results_negative_df

,hgnc_symbol,M10237,M1036,M10501,M11961,M12113,M13893,M14427,M149,M15619,...,GO:0042776,GO:0043412,GO:0043687,GO:0044248,GO:0044281,GO:0044419,GO:0046034,GO:0070647,GO:0098727,GO:0140888
0,ABCB4,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,ABHD14B,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,ACER3,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,ACSM2A,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.333333,0.0,0.0,0.0,0.0,0.0
4,ACTL6A,0.066667,0.0,0.0,0.266667,0.0,0.0,0.0,0.461538,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,ZNF695,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
417,ZNF75D,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
418,ZNF835,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
419,ZNF90,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
420,ZNFX1,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,0.0,0.0,0.0

In [24]:
# check duplicated values in the 'hgnc_symbol' column
duplicates_negative = results_negative_df[results_negative_df.duplicated('hgnc_symbol', keep=False)]
duplicates_negative

Empty DataFrame
Columns: [hgnc_symbol, M10237, M1036, M10501, M11961, M12113, M13893, M14427, M149, M15619, M16189, M16975, M1743, M189, M19745, M19806, M2132, M2241, M2325, M2328, M2368, M2534, M27170, M27214, M27621, M27686, M283, M29556, M29813, M3758, M39495, M39736, M4077, M4409, M5275, M5336, M5611, M567, M6782, M80, M864, M9585, GO:0005622, GO:0005634, GO:0005654, GO:0005681, GO:0005739, GO:0005747, GO:0005759, GO:0005813, GO:0005815, GO:0005829, GO:0015630, GO:0030964, GO:0031974, GO:0031981, GO:0031982, GO:0042175, GO:0043025, GO:0043233, GO:0044297, GO:0045271, GO:0070013, GO:0099634, GO:0140513, GO:1902495, GO:1990351, GO:0003824, GO:0005524, GO:0008047, GO:0016491, GO:0016740, GO:0017076, GO:0032553, GO:0032555, GO:0035639, GO:0097367, GO:0098772, GO:0140096, GO:0140657, GO:0140677, GO:0006302, GO:0006397, GO:0006468, GO:0006754, GO:0006974, GO:0010257, GO:0010629, GO:0015986, GO:0016032, GO:0016071, GO:0016236, GO:0016567, GO:0019221, GO:0019827, GO:0032446, GO:0032981, GO:0033108, GO:0034330, GO:0036211, ...]
Index: []

[0 rows x 110 columns]

In [25]:
# Save the DataFrame as a CSV file
results_negative_df.to_csv(r'C:/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/ML_input_files/ClosenessCentrality_tables/msigdb_and_GO/local_basal_negative.csv')